Update final_test.yml

diff --git a/final_test.yml b/final_test.yml
--- a/final_test.yml
+++ b/final_test.yml
@@ -39,23 +39,27 @@
       user_data: |
                 #!/bin/bash
                 
-                retry_attempts=10
-                attempt=0
-                while [[ $attempt -lt $retry_attempts ]]
-                do
-                    curl -k --data "host_config_key=677268f66d49c4a70c95c9f60406588d" https://10.1.41.148:443/api/v2/job_templates/14/callback/
-                    rpm -q tree
-                    status_code=$(echo $?)
+                # retry_attempts=10
+                # attempt=0
+                # while [[ $attempt -lt $retry_attempts ]]
+                # do
+                #     curl -k --data "host_config_key=677268f66d49c4a70c95c9f60406588d" https://10.1.41.148:443/api/v2/job_templates/14/callback/
+                #     rpm -q tree
+                #     status_code=$(echo $?)
                     
-                    if [[ $status_code == 0 ]]
-                        then
-                        exit 0
-                    fi
-                    attempt=$(( attempt + 1 ))
-                    echo "${status_code} received... retrying in 1 minute. (Attempt ${attempt})"
-                    sleep 60s
-                 done
-                 exit 1
+                #     if [[ $status_code == 0 ]]
+                #         then
+                #         exit 0
+                #     fi
+                #     attempt=$(( attempt + 1 ))
+                #     echo "${status_code} received... retrying in 1 minute. (Attempt ${attempt})"
+                #     sleep 60s
+                #  done
+                #  exit 1
+
+                yum install -y httpd
+                echo Ansible test > /var/www/html/index.html
+                service httpd start
 
    - name: Create ELB
      ec2_elb_lb:
